### ISSUE TITLE
Allow to whitelist packages

### ISSUE THREAD

**Issue by gunnarmorling** [moditect/deptective#4]
A whitelisted package can always be read by any other package.

**Comment by nilshartmann** [comment]
Hi @gunnarmorling! I wonder If we shouldn't white list `java.lang` automatically?

**Comment by gunnarmorling** [comment]
> I wonder If we shouldn't white list java.lang automatically?

Yes, I think that'd make sense very much.

**Comment by gunnarmorling** [comment]
Done.
