### ISSUE TITLE
classgraph project

### ISSUE THREAD

**Issue by qoomon** [moditect/deptective#46]
FYI following project might be interesting for your purpose
https://github.com/classgraph/classgraph

**Comment by gunnarmorling** [comment]
Hi, thanks for the pointer. Had looked at it before the rename from Fast Classpath Scanner. Fun fact: ClassGraph is using the ModiTect Maven plug-in for adding a module descriptor to its project :)

That said, I don't think it's beneficial to Deptective's purposes. The reason being that Deptective works on the AST *during* compilation, i.e. no classfiles exist yet at this point. Was there any specific usage you had in mind?

**Comment by qoomon** [comment]
I see. never mind :-D

**Comment by gunnarmorling** [comment]
Thanks nevertheless, always good to exchange and discuss 👍  If you got any other ideas or thoughts around Deptective, please let us know.

**Comment by qoomon** [comment]
Just a feature idea, would be great if you can implement something similar to my solution for ArchUnit https://github.com/TNG/ArchUnit/issues/151. It assert for packages accessing upper/parent packages.

PS: thanks for your talk at javaland
